version: '1.0'

services:

# webserver + php config
  php:
    build: php
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure
    volumes:
      - ./php/www:/var/www/html
    cpus: 1
    mem_limit: 1024m

# graphical mysql access
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
        - db:db
    ports:
        - 8080:80
    restart: on-failure
    environment:
        MYSQL_ROOT_PASSWORD: docker123
    cpus: 1
    mem_limit: 1024m

# mysql database
  db:
    image: mysql:5.7
    ports:
     - "3306:3306"
    volumes:
     - /var/lib/mysql
    restart: on-failure
    environment:
     - MYSQL_ROOT_PASSWORD=docker123
     - MYSQL_DATABASE=database
    cpus: 1
    mem_limit: 1024m

# monitoring gui
  cadvisor:
    image: google/cadvisor:v0.29.0
    links:
      - influxdb:influxsrv
    command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxsrv:8086
    restart: on-failure
    ports:
      - "8888:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    cpus: 1
    mem_limit: 1024m

# monitoring db
  influxdbData:
    image: busybox
    volumes:
      - /var/lib/influxdb
      - ./data/influxdb:/data
 
  influxdb:
    image: tutum/influxdb:0.9
    restart: on-failure
    environment:
      - PRE_CREATE_DB=cadvisor
    ports:
      - "8083:8083"
      - "8086:8086"
    expose:
      - "8090"
      - "8099"
    volumes_from:
      - "influxdbData"
    cpus: 1
    mem_limit: 1024m
